---
title:               GKW
tagline:             adventures in code.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "wazina" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "OmyKiss135" %>
name:                Greg Wallace
twitter:             wallace_greg
github:              wazina
email:               greg@icodeforu.com
google_analytics_id: YOUR_GA_ID